package com.tutorplatform.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * OTP TOKEN ENTITY
 * =====================================================
 * Represents a One-Time Password (OTP) sent to a user
 * for phone/email verification during registration.
 *
 * HOW OTP FLOW WORKS:
 * 1. User registers → OtpService generates a 6-digit code
 * 2. Code is saved here with a 15-minute expiry window
 * 3. SMS + email are sent to the user with the code
 * 4. User visits /verify and enters the code
 * 5. OtpService validates: code matches, not expired, not used
 * 6. If valid → mark user.phoneVerified = true, user.emailVerified = true
 *              → mark this token as used = true (prevents re-use)
 *
 * DESIGN NOTES:
 * - The relationship is OneToOne per user; OtpService replaces any
 *   existing unused token when generating a new one (so requesting a
 *   new OTP invalidates the old one).
 * - The "used" flag prevents the same code from being accepted twice.
 * - OTP codes are plain 6-digit strings (no hashing needed at this
 *   scale, since they expire in 15 minutes).
 *
 * DATABASE TABLE: "otp_tokens"
 * =====================================================
 */
@Entity
@Table(name = "otp_tokens")
public class OtpToken {

    // =====================================================
    // PRIMARY KEY
    // Auto-incremented surrogate key.
    // =====================================================
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // =====================================================
    // OWNER — the user this OTP was generated for
    // =====================================================

    /**
     * The user who must enter this OTP to verify their account.
     * OneToOne relationship: each active OTP belongs to one user.
     * FetchType.LAZY avoids loading the full User object unless needed.
     */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    // =====================================================
    // OTP CODE
    // =====================================================

    /**
     * The 6-digit verification code, e.g. "483921".
     * Generated by OtpService using SecureRandom to ensure
     * cryptographic randomness.
     */
    @Column(nullable = false, length = 6)
    private String code;

    // =====================================================
    // TIMESTAMPS
    // =====================================================

    /**
     * When this OTP was created.
     * Set automatically in OtpService before saving.
     */
    @Column(nullable = false)
    private LocalDateTime createdAt;

    /**
     * When this OTP expires (createdAt + 15 minutes).
     * OtpService rejects tokens where LocalDateTime.now() is after expiresAt.
     */
    @Column(nullable = false)
    private LocalDateTime expiresAt;

    // =====================================================
    // USED FLAG
    // Prevents the same OTP from being accepted more than once.
    // =====================================================

    /**
     * Whether this OTP has already been consumed (successfully validated).
     * Defaults to false.  Set to true immediately after a successful
     * verification to prevent replay attacks.
     */
    @Column(nullable = false)
    private boolean used = false;

    // =====================================================
    // CONSTRUCTORS
    // =====================================================

    /** Default constructor required by JPA */
    public OtpToken() {}

    /**
     * Convenience constructor used by OtpService when creating a new token.
     *
     * @param user      the user to verify
     * @param code      the generated 6-digit code
     * @param createdAt the moment of creation
     * @param expiresAt createdAt + 15 minutes
     */
    public OtpToken(User user, String code, LocalDateTime createdAt, LocalDateTime expiresAt) {
        this.user = user;
        this.code = code;
        this.createdAt = createdAt;
        this.expiresAt = expiresAt;
        this.used = false;
    }

    // =====================================================
    // GETTERS AND SETTERS
    // =====================================================

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public User getUser() { return user; }
    public void setUser(User user) { this.user = user; }

    public String getCode() { return code; }
    public void setCode(String code) { this.code = code; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    public LocalDateTime getExpiresAt() { return expiresAt; }
    public void setExpiresAt(LocalDateTime expiresAt) { this.expiresAt = expiresAt; }

    public boolean isUsed() { return used; }
    public void setUsed(boolean used) { this.used = used; }

    // =====================================================
    // HELPER — quick expiry check
    // =====================================================

    /**
     * Convenience method: returns true if this OTP is still within
     * its validity window AND has not been used yet.
     *
     * @return true if the token is still valid and unused
     */
    public boolean isValid() {
        return !used && LocalDateTime.now().isBefore(expiresAt);
    }

    @Override
    public String toString() {
        return "OtpToken{id=" + id
                + ", userId=" + (user != null ? user.getId() : "null")
                + ", expiresAt=" + expiresAt
                + ", used=" + used + "}";
    }
}
